# Single source of truth for all project status
features:
Cycle 2 Sprint 1:
  C2-S1-A1: "implemented"
  C2-S1-A2: "implemented"
  C2-S1-A3: "implemented"
  C2-S1-A4: "implemented"
  C2-S1-B1: "implemented"  
  C2-S1-B2: "implemented"
  C2-S1-B3a: "implemented"  # State Management Infrastructure (T-1, T-2, T-3)
  C2-S1-B3b: "implemented"  # Cockpit UI Wiring
  C2-S1-B3c: "planned"      # Calendar UI Wiring  
  C2-S1-B3d: "planned"      # Progress UI Wiring
  C2-S1-B3: "draft"         # Original B3 spec (superseded by B3a/B3b/B3c/B3d)
  C2-S2-C1: "planned"

Cycle 2 Sprint 1.5:
  C2-S1.5-Task1: "implemented"  # Database Foundation (Schema + RLS)
  C2-S1.5-Task2: "implemented"  # Auth Middleware (JWT verification, error classes)
  C2-S1.5-Task3: "implemented"  # Auth Routes (signup, login, logout, reset, session)

policies:
  etag-policy: "active"
  auth-mapping: "active"
  ci-gates: "active"