# Single source of truth for all project status
features:
Cycle 2 Sprint 1:
  C2-S1-A1: "implemented"
  C2-S1-A2: "implemented"
  C2-S1-A3: "implemented"
  C2-S1-A4: "implemented"
  C2-S1-B1: "implemented"  
  C2-S1-B2: "implemented"
  C2-S1-B3: "draft" 
  C2-S2-C1: "planned"

policies:
  etag-policy: "active"
  auth-mapping: "active"
  ci-gates: "active"