name: docs-guard

on:
  pull_request:
    branches: [ main ]

jobs:
  docs-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if code touched requires a spec
        run: |
          set -euo pipefail
          BASE="${{ github.base_ref || 'main' }}"
          CHANGED=$(git diff --name-only "origin/${BASE}...HEAD" || true)

          requires_spec=false
          echo "$CHANGED" | grep -E '^(app/api/|pages/api/|openapi/|supabase/migrations/|lib/|docs/policy/)' && requires_spec=true || true

          if [ "$requires_spec" = true ]; then
            echo "Code touched that requires a spec. Verifying docs/specs/* present in PR…"
            echo "$CHANGED" | grep -E '^docs/specs/.+\.md$' >/dev/null || {
              echo "::error::Missing feature spec in docs/specs/*.md for this PR."
              echo "Touching API/openapi/migrations or policies requires a spec doc."
              exit 1
            }
          else
            echo "No guarded paths changed."
          fi